baseURL = 'https://your-domain.com/'
languageCode = 'zh-cn'
title = '我的知识库'
theme = 'hugo-theme-docdock'

[params]
  description = "个人知识库"
  editURL = "https://github.com/kyeo-hub/my_wiki/edit/main/content"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"
  disableSearch = false
  disableHistory = true
  disableNavChevron = false

  [params.author]
    name = "kyeo"
    email = "your-email@example.com"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

# 多语言配置（可选）
[languages]
  [languages.zh]
    title = "我的知识库"
    weight = 1
    languageName = "中文"
  [languages.en]
    title = "My Wiki"
    weight = 2
    languageName = "English"
